#!/bin/bash
for i in $(seq 1 100); do 
	sed "${i}q;d" forge.100.or  | sed "s/ *SLASH */\//g" | sed "s/ *COLON */:/g" | sed "s/ *DOLLAR */$ /g" | sed "s/PIPE/|/g" | sed "s/ POINT */\./g" | sed "s/ COMMA /,/g" | sed "s/ LCBRACE /{/g" | sed "s/ RCBRACE */}/g" | sed "s/ *PLUS */+/g" | sed "s/ LESSTHAN /</g" | sed "s/ GREATERTHAN/>/g" | sed "s/ APOSTROPHE /'/g" | sed "s/ LBRACKET /(/g"  | sed "s/ RBRACKET /)/g" | sed "s/ APOSTROPHE /'/g" | sed "s/ DASH /-/g" | sed "s/ AMPERSAND /&/g"  | sed "s/ DOUBLEQUOTE /\"/g" | sed "s/ UNDERSCORE /_/g" | sed "s/ FORWARDSLASH /\//g" | sed "s/BLANK//g"| sed "s/ *NEWLINE */\\n/g" | sed "s/ *MINUS */-/g" | sed -r "s/([^ ])(\+[0-9]+\/\+[0-9]+)/\1 \2/g"; 
	echo "----------"; 
	sed "${i}q;d" forge.100.sc  | sed "s/ *SLASH */\//g" | sed "s/ *COLON */:/g" | sed "s/ *DOLLAR */$ /g" | sed "s/PIPE/|/g" | sed "s/ POINT */\./g" | sed "s/ COMMA /,/g" | sed "s/ LCBRACE /{/g" | sed "s/ RCBRACE */}/g" | sed "s/ *PLUS */+/g" | sed "s/ LESSTHAN /</g" | sed "s/ GREATERTHAN/>/g" | sed "s/ APOSTROPHE /'/g" | sed "s/ LBRACKET /(/g"  | sed "s/ RBRACKET /)/g" | sed "s/ APOSTROPHE /'/g" | sed "s/ DASH /-/g" | sed "s/ AMPERSAND /&/g"  | sed "s/ DOUBLEQUOTE /\"/g" | sed "s/ UNDERSCORE /_/g" | sed "s/ FORWARDSLASH /\//g" | sed "s/BLANK//g"| sed "s/ *NEWLINE */\\n/g" | sed "s/ *MINUS */-/g" | sed -r "s/([^ ])(\+[0-9]+\/\+[0-9]+)/\1 \2/g";
        echo "----------";
	sed "${i}q;d" output_dev  | sed "s/ *SLASH */\//g" | sed "s/ *COLON */:/g" | sed "s/ *DOLLAR */$ /g" | sed "s/PIPE/|/g" | sed "s/ POINT */\./g" | sed "s/ COMMA /,/g" | sed "s/ LCBRACE /{/g" | sed "s/ RCBRACE */}/g" | sed "s/ *PLUS */+/g" | sed "s/ LESSTHAN /</g" | sed "s/ GREATERTHAN/>/g" | sed "s/ APOSTROPHE /'/g" | sed "s/ LBRACKET /(/g"  | sed "s/ *RBRACKET */)/g" | sed "s/ *APOSTROPHE */'/g" | sed "s/ DASH /-/g" | sed "s/ AMPERSAND /&/g"  | sed "s/ DOUBLEQUOTE /\"/g" | sed "s/ UNDERSCORE /_/g" | sed "s/ *FORWARDSLASH */\//g" | sed "s/BLANK//g"| sed "s/ *NEWLINE */\\n/g" | sed "s/ *MINUS */-/g" | sed -r "s/([^ ])(\+[0-9]+\/\+[0-9]+)/\1 \2/g"; 
	echo "================================"; 
done
